version:"3"
serices: 
  db: 
      image: postgres:latest
      restart : always
      ports:
        - "5432:5432"
        enviroment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "password"
        volumes: 
          - ./data:/var/lib/postgresql/data